#!/bin/bash

set -o nounset
set -o errexit

cd "$(dirname $0)"
cd ../

origin_ifs="$IFS"
IFS=$'\n'
script_name="post-update"
script_file="git-hooks/$script_name"
script_md5=$(md5sum "$script_file" | awk '{ print $1 }')

for item in $(find -name 'hooks' -path '*/*.git/*' ! -path '*/git-hooks/*'); do
    dest_file="$item/$script_name"
    if test -e "$dest_file"; then
        dest_md5=$(md5sum "$dest_file" | awk '{ print $1 }')
	if [[ $script_md5 == $dest_md5 ]]; then
            # 如果脚本的 md5 完全相同，则认为两个文件完全相同，不需要复制文件
	    continue
	fi
    fi
    cp -v "git-hooks/$script_name" "$item"
done

IFS="$origin_ifs"
